name: base_project_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+13

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  awesome_dialog: ^2.1.1
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.6
  argon_buttons_flutter: 
  google_fonts: 2.2.0
  flutter_local_notifications: 9.1.0
  firebase_core:
  firebase_messaging:
  firebase_database: 9.0.16
  dropdown_button2: ^1.0.6
  modal_bottom_sheet: ^2.0.0
  flutter_spinkit: 5.1.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.7
  sizer: ^2.0.15
  flutter_screen_lock: ^5.0.12
  path_provider: ^2.0.11
  intl: ^0.17.0
  veriff_flutter: ^2.2.0
  firebase_analytics:
  lottie: ^1.3.0
  page_transition: ^2.0.9
  change_app_package_name: ^1.1.0
  flutter_datetime_picker:
  flutter_stripe: null
  url_launcher: ^6.1.5
  flutter_holo_date_picker: ^1.0.6
  date_utils: ^0.2.0
  pay: ^1.0.10
  firebase_storage: ^10.3.8
  encrypt: ^5.0.1
  credit_card_validator: ^2.0.1
  provider: ^6.0.3
  cupertino_back_gesture: ^0.1.0
  intercom_flutter: 7.6.0
  upgrader:
  facebook_app_events: ^0.18.3
  onesignal_flutter:
  flutter_segment: ^3.12.1
  flutter_smartlook: ^4.0.6
  survicate_flutter_sdk: ^2.1.2
  mixpanel_flutter:
  syncfusion_flutter_charts: ^20.4.44
  appsflyer_sdk: ^6.9.3
  loading_icon_button:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  pay_ios: 1.0.7
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - images/C1.png
    - images/C2.png
    - images/C3.png
    - images/C4.png
    - images/T11.png
    - images/T21.png
    - images/T31.png
    - images/T41.png
    - images/logo.png
    - images/des2.png
    - images/V1.png
    - images/ID.png
    - images/euro.png
    - images/Bank.png
    - images/ApplePay.png
    - images/close.png
    - images/yes.png
    - images/no.png
    - images/30m1.png
    - images/30m2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-SemiBold.ttf
    - family: SignikaB
      fonts:
        - asset: fonts/Signika-Bold.ttf
    - family: SignikaL
      fonts:
        - asset: fonts/Signika-Light.ttf
    - family: SignikaM
      fonts:
        - asset: fonts/Signika-Medium.ttf
    - family: SignikaS
      fonts:
        - asset: fonts/Signika-SemiBold.ttf
    - family: SignikaR
      fonts:
        - asset: fonts/Signika-Regular.ttf

    # - family: Barlow-Bold
    #   fonts:
    #     - asset: assets/fonts/Barlow-Bold.
    #       weight: 100
    #     - asset: fonts/Signika-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-
module:
  androidX: true # Add this line.
